# UpgradeData.gd
extends Node


var upgrades: Dictionary = {
	"Scrapyard":{
		"Speed":{
			"id": 0,
			"name": "Speed",
			"level": 0,
			"max_level": 10,
			"base_cost": 5,
			"cost": 5,
			"cost_scaling": 1.2,
			"type": "stat",
			"currency": "money",
			"first_upgarde": false, #if there is a buy bonus for first upgrade
			"first_description":"",  #if there is a buy bonus for first upgrade
			"description": "Increases player speed",
			"sprite_position": Vector2(0,0),
		},
		"Strength": {
			"id": 1,
			"name": "Strength",
			"level": 0,
			"max_level": 10,
			"base_cost": 7,
			"cost": 7,
			"cost_scaling": 1.2,
			"type": "stat",
			"currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Push items faster, and move heavier items",
			"sprite_position": Vector2(1, 0),
		},
		"SpawnRate": {
			"id": 2,
			"name": "Spawn Rate",
			"level": 0,
			"max_level": 20,
			"base_cost": 25,
			"cost": 25,
			"cost_scaling": 1.6,
			"type": "stat",
			"currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Items spawn more frequently",
			"sprite_position": Vector2(2, 0),
		},
		"Rarity": {
			"id": 3,
			"name": "Rarity",
			"level": 0,
			"max_level": 8,
			"base_cost": 35,
			"cost": 35,
			"cost_scaling": 1.5,
			"type": "stat",
			"currency": "money",
			"first_upgrade": true,
			"first_description": "Allow items of higher rarity to spawn",
			"description": "Increases the chance to spawn treasure",
			"sprite_position": Vector2(3, 0),
		},
		"ItemFocuser": {
			"id": 4,
			"name": "Item Focuser",
			"level": 0,
			"max_level": 6,
			"base_cost": 150,
			"cost": 150,
			"cost_scaling": 5.0,
			"type": "custom","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Items are more likely to spawn closer to the collection point",
			"sprite_position": Vector2(0, 1),
		},
		"Combo": {
			"id": 5,
			"name": "Combo",
			"level": 0,
			"max_level": 5,
			"base_cost": 250,
			"cost": 250,
			"cost_scaling": 1.7,
			"type": "custom","currency": "money",
			"first_upgrade": true,
			"first_description": "Robot can now combo giving multiplier on sales",
			"description": "increase chance for combo to start",
			"sprite_position": Vector2(1, 1),
		},
		"ComboIncrease": {
			"id": 6,
			"name": "Combo Increase",
			"level": 0,
			"max_level": 100,
			"base_cost": 750,
			"cost": 750,
			"cost_scaling": 1.7,
			"type": "stat","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Increases the value of your combos",
			"sprite_position": Vector2(2, 1),
		},
		"SurgeProtection": {
			"id": 7,
			"name": "Surge Protection",
			"level": 0,
			"max_level": 5,
			"base_cost": 2500,
			"cost": 2500,
			"cost_scaling": 1.6,
			"type": "custom","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Lessens the effect of power surge in underground",
			"sprite_position": Vector2(3, 1),
		},
	},
	"Underground":{
		"SurgeRedistributor":{
			"id": 8,
			"name": "Surge Redistributor",
			"level": 0,
			"max_level": 5,
			"base_cost": 3000,
			"cost": 3000,
			"cost_scaling": 1.2,
			"type": "custom","currency": "money",
			"first_upgrade": true,
			"first_description": "Chance to boost earnings and player speed during power surges",
			"description": "Increases chance to surge",
			"sprite_position": Vector2(0,2),
		},
		"Rarity+": {
			"id": 9,
			"name": "Rarity+",
			"level": 0,
			"max_level": 8,
			"base_cost": 4000,
			"cost": 4000,
			"cost_scaling": 1.5,
			"type": "custom","currency": "money",
			"first_upgrade": true,
			"first_description": "Allows even rarer items to spawn",
			"description": "Further increases rare item chances",
			"sprite_position": Vector2(1,2),
		},
		"SuperCombo": {
			"id": 10,
			"name": "Super Combo",
			"level": 0,
			"max_level": 4,
			"base_cost": 6000,
			"cost": 6000,
			"cost_scaling": 2.0,
			"type": "custom","currency": "money",
			"first_upgrade": true,
			"first_description": "Enables 10X boost for extended combos",
			"description": "Increases super combo duration window",
			"sprite_position": Vector2(2,2),
		},
		"SuperComboAligner": {
			"id": 11,
			"name": "Super Combo Aligner",
			"level": 0,
			"max_level": 4,
			"base_cost": 2500,
			"cost": 2500,
			"cost_scaling": 1.9,
			"type": "stat","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Reduces time needed for super combo",
			"sprite_position": Vector2(3,2),
		},
		"BasicWaterproofing": {
			"id": 12,
			"name": "Basic Waterproofing",
			"level": 0,
			"max_level": 3,
			"base_cost": 15000,
			"cost": 15000,
			"cost_scaling": 2.5,
			"type": "custom","currency": "money",
			"first_upgrade": true,
			"first_description": "Allows limited survival in water",
			"description": "Increases underwater survival time",
			"sprite_position": Vector2(0,3),
		},
		"SurgeChances": {
			"id": 13,
			"name": "Surge Chances",
			"level": 0,
			"max_level": 10,
			"base_cost": 1000,
			"cost": 1000,
			"cost_scaling": 1.3,
			"type": "stat","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Increases power surge frequency",
			"sprite_position": Vector2(1,3),
		},
		"Companion": {
			"id": 14,
			"name": "Companion",
			"level": 0,
			"max_level": 6,
			"base_cost": 15000,
			"cost": 15000,
			"cost_scaling": 5.0,
			"type": "custom","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "gain a companion to help push scrap",
			"sprite_position": Vector2(2,3),
		},
		"Refinement": {
			"id": 15,
			"name": "Refinement",
			"level": 0,
			"max_level": 30,
			"base_cost": 2000,
			"cost": 2000,
			"cost_scaling": 1.8,
			"type": "stat","currency": "money",
			"first_upgrade": true,
			"first_description": "Trash items give 1% income boost (max 500%)",
			"description": "Increases max boost cap by 100% per level",
			"sprite_position": Vector2(3,3),
		},
	},
	"Ocean":{
		"Rarity++":{
			"id": 16,
			"name": "Rarity++",
			"level": 0,
			"max_level": 8,
			"base_cost": 30000,
			"cost": 30000,
			"cost_scaling": 1.5,
			"type": "custom","currency": "money",
			"first_upgrade": true,
			"first_description": "Spawns ultra-rare items with increased value",
			"description": "Further increases item value multiplier",
			"sprite_position": Vector2(0,4),
		},
		"CompanionUpgrades": {
			"id": 17,
			"name": "Companion Upgrades",
			"level": 0,
			"max_level": 1,
			"base_cost": 25000,
			"cost": 25000,
			"cost_scaling": 1.5,
			"type": "stat","currency": "money",
			"first_upgrade": true,
			"first_description": "",
			"description": "Unlocks companion upgrades",
			"sprite_position": Vector2(1,4),
		},
		"WaterProof": {
			"id": 20,
			"name": "Water Proof",
			"level": 0,
			"max_level": 4,
			"base_cost": 40000,
			"cost": 40000,
			"cost_scaling": 1.1,
			"type": "custom","currency": "money",
			"first_upgrade": true,
			"first_description": "Enables unlimited underwater operation",
			"description": "Enables unlimited underwater operation, and increase health",
			"sprite_position": Vector2(2,4),
		},
		"Prestige": {
			"id": 21,
			"name": "Prestige",
			"level": 0,
			"max_level": 1,
			"base_cost": 10000,
			"cost": 10000,
			"cost_scaling": 1.0,
			"type": "custom","currency": "money",
			"first_upgrade": true,
			"first_description": "Resets progress for power crystals",
			"description": "Resets progress for power crystals, unlocks power crystal shop",
			"sprite_position": Vector2(3,4),
		},
		"SeaDrill": {
			"id": 22,
			"name": "Sea Drill",
			"level": 0,
			"max_level": 20,
			"base_cost": 5000,
			"cost": 5000,
			"cost_scaling": 1.4,
			"type": "stat","currency": "money",
			"first_upgrade": true,
			"first_description": "Automatically generates income",
			"description": "Increases drill production rate",
			"sprite_position": Vector2(0,5),
		},
		"DrillBurst": {
			"id": 23,
			"name": "Drill Burst",
			"level": 0,
			"max_level": 10,
			"base_cost": 35000,
			"cost": 35000,
			"cost_scaling": 1.7,
			"type": "stat","currency": "money",
			"first_upgrade": true,
			"first_description": "chance to for drills to burst with scrap and treasure",
			"description": "drill burst gives more scrap, of higher rarity",
			"sprite_position": Vector2(1,5),
		},
	},
	"Alien":{
		"Rarity+++":{
			"id": 24,
			"name": "Rarity+++",
			"level": 0,
			"max_level": 8,
			"base_cost": 50000,
			"cost": 50000,
			"cost_scaling": 1.5,
			"type": "custom","currency": "money",
			"first_upgrade": true,
			"first_description": "Spawns alien artifacts with massive value",
			"description": "Further increases alien item value",
			"sprite_position": Vector2(0,6),
		},
		"Armour": {
			"id": 25,
			"name": "Armour",
			"level": 0,
			"max_level": 10,
			"base_cost": 30000,
			"cost": 30000,
			"cost_scaling": 1.8,
			"type": "stat","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Increases player health",
			"sprite_position": Vector2(1,6),
		},
		"AutoCombo": {
			"id": 26,
			"name": "Auto Combo",
			"level": 0,
			"max_level": 5,
			"base_cost": 60000,
			"cost": 60000,
			"cost_scaling": 2.2,
			"type": "stat","currency": "money",
			"first_upgrade": true,
			"first_description": "Slowly builds combos automatically",
			"description": "Increases auto-combo speed",
			"sprite_position": Vector2(2,6),
		},
		"AlienInterface": {
			"id": 27,
			"name": "Alien Interface",
			"level": 0,
			"max_level": 5,
			"base_cost": 75000,
			"cost": 75000,
			"cost_scaling": 2.5,
			"type": "stat","currency": "money",
			"first_upgrade": true,
			"first_description": "Chance to convert alien patrols to companions",
			"description": "Increases conversion chance",
			"sprite_position": Vector2(3,6),
		},
		"AlienRefinement": {
			"id": 28,
			"name": "Alien Refinement",
			"level": 0,
			"max_level": 10,
			"base_cost": 100000,
			"cost": 100000,
			"cost_scaling": 3.0,
			"type": "stat","currency": "money",
			"first_upgrade": true,
			"first_description": "10% value boost per item (max 1e6%)",
			"description": "Increases cap by 1000% per level",
			"sprite_position": Vector2(0,7),
		},
		"AlienSignal": {
			"id": 29,
			"name": "Alien Signal",
			"level": 0,
			"max_level": 5,
			"base_cost": 50000,
			"cost": 50000,
			"cost_scaling": 2.0,
			"type": "stat","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Increases patrol spawn frequency",
			"sprite_position": Vector2(1,7),
		},
		"AlienController": {
			"id": 30,
			"name": "Alien Controller",
			"level": 0,
			"max_level": 3,
			"base_cost": 200000,
			"cost": 200000,
			"cost_scaling": 4.0,
			"type": "stat","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Increases alien companion duration",
			"sprite_position": Vector2(2,7),
		},
		"Synergy": {
			"id": 31,
			"name": "Synergy",
			"level": 0,
			"max_level": 5,
			"base_cost": 150000,
			"cost": 150000,
			"cost_scaling": 3.5,
			"type": "stat","currency": "money",
			"first_upgrade": true,
			"first_description": "777X value with 5+ companions",
			"description": "Reduces required companion count",
			"sprite_position": Vector2(3,7),
		}
	},
	"Power_Crystal":{
		"3XSellValue":{
			"id": 32,
			"name": "3X Sell Value",
			"level": 0,
			"max_level": 100,
			"base_cost": 5,
			"cost": 5,
			"cost_scaling": 2.5,
			"type": "custom","currency": "powerC",
			"first_upgrade": false,
			"first_description": "All items sell for 3X their normal value",
			"description": "All items sell for 3X their normal value",
			"sprite_position": Vector2(0,8),
		},
		"3XComboValue": {
			"id": 33,
			"name": "3X Combo Value",
			"level": 0,
			"max_level": 25,
			"base_cost": 5,
			"cost": 5,
			"cost_scaling": 3,
			"type": "custom","currency": "powerC",
			"first_upgrade": false,
			"first_description": "All combo multipliers are 3X more effective",
			"description": "All combo multipliers are 3X more effective",
			"sprite_position": Vector2(1,8),
		},
		"AlienKey": {
			"id": 34,
			"name": "Alien Key",
			"level": 0,
			"max_level": 1,
			"base_cost": 10,
			"cost": 10,
			"cost_scaling": 1.0,
			"type": "custom","currency": "powerC",
			"first_upgrade": true,
			"first_description": "Unlocks the Hidden Alien Dumping Grounds",
			"description": "you can now enter the Alien Dumping Grounds with money",
			"sprite_position": Vector2(2,8),
		},
		"KeepLocations": {
			"id": 35,
			"name": "Keep Locations",
			"level": 0,
			"max_level": 1,
			"base_cost": 15,
			"cost": 15,
			"cost_scaling": 1.0,
			"type": "custom","currency": "powerC",
			"first_upgrade": true,
			"first_description": "Retain unlocked locations after reset",
			"description": "Location retained",
			"sprite_position": Vector2(3,8),
		},
		"PowerCrystalValue": {
			"id": 36,
			"name": "Power Crystal Value",
			"level": 0,
			"max_level": 150,
			"base_cost": 10,
			"cost": 10,
			"cost_scaling": 2.5,
			"type": "stat","currency": "powerC",
			"first_upgrade": false,
			"first_description": "",
			"description": "Earn more crystals from each reset",
			"sprite_position": Vector2(0,9),
		},
		"KeepCompanions": {
			"id": 37,
			"name": "Keep Companions",
			"level": 0,
			"max_level": 1,
			"base_cost": 20,
			"cost": 20,
			"cost_scaling": 1.0,
			"type": "custom","currency": "powerC",
			"first_upgrade": true,
			"first_description": "Retain all companions after reset",
			"description": "Companions retained",
			"sprite_position": Vector2(1,9),
		},
		"Magnet": {
			"id": 38,
			"name": "Magnet",
			"level": 0,
			"max_level": 10,
			"base_cost": 10,
			"cost": 10,
			"cost_scaling": 1.5,
			"type": "stat","currency": "powerC",
			"first_upgrade": true,
			"first_description": "Items near collector auto-collect",
			"description": "Increases magnet range",
			"sprite_position": Vector2(2,9),
		},
		"Transformation": {
			"id": 39,
			"name": "Transformation",
			"level": 0,
			"max_level": 1,
			"base_cost": 50,
			"cost": 50,
			"cost_scaling": 1.0,
			"type": "custom","currency": "powerC",
			"first_upgrade": true,
			"first_description": "Alien-enhanced body (no expulsion from Alien Base + stat boosts)",
			"description": "",
			"sprite_position": Vector2(3,9),
		},
		"IncreaseUpgradeLevelCap": {
			"id": 40,
			"name": "Increase Upgrade Level Cap",
			"level": 0,
			"max_level": 5,
			"base_cost": 25,
			"cost": 25,
			"cost_scaling": 3.0,
			"type": "stat","currency": "powerC",
			"first_upgrade": false,
			"first_description": "",
			"description": "Raises level cap for certain upgrades",
			"sprite_position": Vector2(0,10),
		},
		"EasyCombo": {
			"id": 41,
			"name": "Easy Combo",
			"level": 0,
			"max_level": 5,
			"base_cost": 15,
			"cost": 15,
			"cost_scaling": 1.8,
			"type": "stat","currency": "powerC",
			"first_upgrade": false,
			"first_description": "",
			"description": "+1 allowed combo miss per level",
			"sprite_position": Vector2(1,10),
		},
		"CompanionBoost": {
			"id": 42,
			"name": "Companion Boost",
			"level": 0,
			"max_level": 10,
			"base_cost": 20,
			"cost": 20,
			"cost_scaling": 1.6,
			"type": "stat","currency": "powerC",
			"first_upgrade": false,
			"first_description": "",
			"description": "Earn more with each active companion",
			"sprite_position": Vector2(2,10),
		},
	},
	"Companion": {
		"CompanionSpeed": {
			"id": 43,
			"name": "Companion Speed",
			"level": 0,
			"max_level": 10,
			"base_cost": 2000,
			"cost": 2000,
			"cost_scaling": 1.6,
			"type": "stat","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Earn more with each active companion",
			"sprite_position": Vector2(0,11),
		},
		"CompanionStrength": {
			"id": 44,
			"name": "Companion Strength",
			"level": 0,
			"max_level": 10,
			"base_cost": 20,
			"cost": 20,
			"cost_scaling": 1.6,
			"type": "stat","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Earn more with each active companion",
			"sprite_position": Vector2(1,11),
		},
		"CompanionCapacity": {
			"id": 45,
			"name": "Companion Capacity",
			"level": 0,
			"max_level": 10,
			"base_cost": 20,
			"cost": 20,
			"cost_scaling": 1.6,
			"type": "stat","currency": "money",
			"first_upgrade": false,
			"first_description": "",
			"description": "Earn more with each active companion",
			"sprite_position": Vector2(2,11),
		},
	}
}
